#!/usr/bin/env python

from typing import Literal, TypedDict, NotRequired
import pathlib
import sys
import json


class AnswersType(TypedDict):
    license: Literal["MIT", "BSD", "GPLv3", "Apache Software License 2.0", "Not open source"]


class Input(TypedDict):
    answers: AnswersType
    template_dir: str
    output_dir: str


def main():
    context: Input = json.load(sys.stdin)
    path = pathlib.Path()
    output_dir_path = path / context["output_dir"]
    template_dir_path = path / context["template_dir"]

    if context["answers"]["license"] != "Not open source":
        with open(template_dir_path / "licenses" / context["answers"]["license"], "r") as f:
            licence_content = f.read()

        with open(output_dir_path / "LICENSE", "w") as f:
            f.write(licence_content)

if __name__ == "__main__":
    main()
